export const DELAY_END_BLOCK = 2000;
export const DELAY_FAILED_HEALTH_CHECK = 10000;
export const DELAY_LOOKUP_BLOCK = 2000;
export const DELAY_ERROR = 10000;

export const CONTRACT_TYPE_UNKNOWN = 0;
export const CONTRACT_TYPE_ARC72 = 1;
export const CONTRACT_TYPE_MP = 2;
export const CONTRACT_TYPE_ARC200 = 3;
export const CONTRACT_TYPE_LPT = 4;
export const CONTRACT_TYPE_STAKE = 5;
export const CONTRACT_TYPE_SCS = 6;

export const ZERO_ADDRESS =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ";
